include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    avoid_renaming_method_parameters: false
    omit_local_variable_types: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    library_private_types_in_public_api: false

analyzer:
  exclude: 
    - "**/*.*.dart" # Generated files
  language:
    strict-raw-types: true
