include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    avoid_renaming_method_parameters: false
    omit_local_variable_types: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
      
  
analyzer:
  exclude: 
    - "**/*.mocks.dart"
    - "**/app.locator.dart"
    - "**/app.router.dart"
    - "**/app.logger.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore