name: ranker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.0.1
  stacked_services: ^0.9.8
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  firebase_ui_auth: ^1.1.3
  firebase_ui_oauth_google: ^1.0.10
  cloud_firestore_odm: ^1.0.0-dev.44
  json_annotation: ^4.7.0
  cloud_firestore: ^4.3.0
  file_picker: ^5.2.4
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^0.8.1
  build_runner: ^2.3.3
  cloud_firestore_odm_generator: ^1.0.0-dev.44
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
