// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVJKcwy7w9ZGphOPTwWWK-7FWtOcLIyU',
    appId: '1:671162613596:web:1d7aa9d6f138de50948b99',
    messagingSenderId: '671162613596',
    projectId: 'ranker-f37f3',
    authDomain: 'ranker-f37f3.firebaseapp.com',
    storageBucket: 'ranker-f37f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1o68s7Ap3xNasE0HBFIYBPbAsb6F9_o',
    appId: '1:671162613596:android:3acee79e3a853df7948b99',
    messagingSenderId: '671162613596',
    projectId: 'ranker-f37f3',
    storageBucket: 'ranker-f37f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ZgK67mDzXDbwVDky8475hKn7bYiPSSk',
    appId: '1:671162613596:ios:1c4fe0ba107967b0948b99',
    messagingSenderId: '671162613596',
    projectId: 'ranker-f37f3',
    storageBucket: 'ranker-f37f3.appspot.com',
    androidClientId: '671162613596-b92appro847in5eur0jmubfnqf5qakqt.apps.googleusercontent.com',
    iosClientId: '671162613596-dneu3le3m9s873qo07fl91qotf8ns55e.apps.googleusercontent.com',
    iosBundleId: 'com.hultergard.ranker.ranker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ZgK67mDzXDbwVDky8475hKn7bYiPSSk',
    appId: '1:671162613596:ios:1c4fe0ba107967b0948b99',
    messagingSenderId: '671162613596',
    projectId: 'ranker-f37f3',
    storageBucket: 'ranker-f37f3.appspot.com',
    androidClientId: '671162613596-b92appro847in5eur0jmubfnqf5qakqt.apps.googleusercontent.com',
    iosClientId: '671162613596-dneu3le3m9s873qo07fl91qotf8ns55e.apps.googleusercontent.com',
    iosBundleId: 'com.hultergard.ranker.ranker',
  );
}
